---
- hosts: all
  become: true

  tasks: 
  - name: creating files to node
    file:
     path: /opt/testfile
     state: touch
     mode: 0755
     owner: ansadmin
     group: ansadmin

  - name: create a directory
    file:
     path: /opt/sai_dir1
     state: directory
     mode: 0755
     owner: ansadmin
     group: ansadmin

  - name: delete a file or directory
    file:
     path: /opt/sai_dir1
     state: absent  

  - name: delete a file or directory
    file:
     path: /opt/testfile
     state: absent

