---
- hosts: all
  become: true
  gather_facts: true

  tasks:
  - name: creating user
    user:
      name: Mounika

  - name: install httpd package
    yum:
      name: httpd
      state: present

  - name: start httpd service
    service:
      name: httpd
      state: started

  - name: copy index.html to access in the browser
    copy:
      src: /home/ansadmin/index.html
      dest: /var/www/html 
