---
- hosts: all
  become: true

  tasks:
  - name: installing httpd on redhat
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"

  - name: install httpd on ubuntu
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: start service in redhat
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"

  - name: start service in ubuntu
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"

  - name: copy index.html file
    copy:
      src: /home/ansadmin/index.html
      dest: /var/www/html

